# Generated by Django 5.0.7 on 2024-08-08 15:17

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='เบอร์โทรติดต่อ')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='ที่อยู่')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='จังหวัด')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='อำเภอ')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='รหัสไปรษณีย์')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.BooleanField(default=False, verbose_name='เปิดให้เช็คอิน')),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('des', models.CharField(max_length=255, verbose_name='คำอธิบาย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=255, verbose_name='ละติจูด')),
                ('lng', models.CharField(max_length=255, verbose_name='ลองจิจูด')),
                ('map_link', models.URLField(max_length=255, verbose_name='google map')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาบันทึก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile.png', upload_to=core.models.profile_image_path)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_image', models.ImageField(upload_to=core.models.slip_image_path, verbose_name='สลีป')),
                ('cost', models.FloatField(verbose_name='จำนวนเงิน')),
                ('approve', models.BooleanField(default=False, verbose_name='อนุมัติ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาบันทึก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
