# Generated by Django 5.0.7 on 2024-08-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationNotMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=255, verbose_name='นามสกุล')),
                ('lat', models.CharField(max_length=255, verbose_name='ละติจูด')),
                ('lng', models.CharField(max_length=255, verbose_name='ลองจิจูด')),
                ('map_link', models.URLField(max_length=255, verbose_name='google map')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาบันทึก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ตำแหน่งผู้ใช้งานที่ไม่ใช่สมาชิก',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'ที่อยู่ลูกค้า'},
        ),
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name_plural': 'เครดิต'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'ตำแหน่งของลูกค้า'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'โปรไฟล์'},
        ),
        migrations.AlterModelOptions(
            name='slip',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'หลักฐานการโอนเงิน'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
