# Generated by Django 5.0.7 on 2024-08-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'ที่อยู่ลูกค้า'},
        ),
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name_plural': 'เครดิต'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'ตำแหน่งของลูกค้า'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'โปรไฟล์'},
        ),
        migrations.AlterModelOptions(
            name='slip',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'หลักฐานการโอนเงิน'},
        ),
    ]
